// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as record$0 from "../../github.com/andreykaipov/goobs/api/requests/record/models.js";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Connect() {
    let $resultPromise = /** @type {any} */($Call.ByID(363021045));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Disconnect() {
    let $resultPromise = /** @type {any} */($Call.ByID(701423063));
    return $resultPromise;
}

/**
 * @returns {Promise<record$0.GetRecordStatusResponse | null> & { cancel(): void }}
 */
export function GetRecordStatus() {
    let $resultPromise = /** @type {any} */($Call.ByID(1496235820));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function PauseRecord() {
    let $resultPromise = /** @type {any} */($Call.ByID(3397289904));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ResumeRecord() {
    let $resultPromise = /** @type {any} */($Call.ByID(1340015923));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ScreenShot() {
    let $resultPromise = /** @type {any} */($Call.ByID(1776714469));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StartRecord() {
    let $resultPromise = /** @type {any} */($Call.ByID(2149788386));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StopRecord() {
    let $resultPromise = /** @type {any} */($Call.ByID(1892552864));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = record$0.GetRecordStatusResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
